title:             def grcanosa
email:             grcanosa@gmail.com
description:       Programming tricks and other tech-related goodies.
author:            grcanosa
baseurl:           ""
url:               "http://grcanosa.github.io"

# Social Profiles
twitter_username:  grcanosa
github_username:   grcanosa
linkedin_username: grcanosa
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
